### ISSUE TITLE
This configuration does not support Terraform version 1.8.0

### ISSUE THREAD

**Issue by ilsl** [dependabot/cli#329]
In the dependabot docs, it supports version 1.8.0
<img width="498" alt="image" src="https://github.com/dependabot/cli/assets/9089050/a04c5ce6-df80-4d58-abf4-b4291da088ae">

However when I run `dependabot update - f job.json` I encounter the following error
``` 
2:   required_version = \"~\u003e 1.7.0\"\n\nThis configuration does not support Terraform version 1.8.0. To proceed,\neither choose another supported Terraform version or update this version\nconstraint.
```

**Comment by jakecoffman** [comment]
Since your `tf` file has the constraint `required_version = "~> 1.7.0"` and Dependabot runs Terraform 1.8.0, Terraform refuses to continue. You can make the constraint more permissive `required_version = ">= 1.7.0"` to fix this. 

There's also an open issue to support any required version https://github.com/dependabot/dependabot-core/issues/5797

Either way this isn't an issue with the Dependabot CLI, so I am going to close this out.

**Comment by ilsl** [comment]
Thank you for the response Jake
